export function getDomRefs() {
  return {
    board: document.getElementById("board"),
    boardWrapper: document.querySelector(".board-wrapper"),
    boardContent: document.getElementById("board-content"),
    hintButton: document.getElementById("hint-button"),
    newGameButton: document.getElementById("new-game-button"),
    undoButton: document.getElementById("undo-button"),
    arenaTurnIndicator: document.getElementById("arena-turn-indicator"),
    turnPlayer: document.getElementById("turn-player"),
    statusMessage: document.getElementById("status-message"),
    scorePanel: document.getElementById("score-panel"),
    setupModal: document.getElementById("setup-modal"),
    setupGridSize: document.getElementById("setup-grid-size"),
    setupExtension: document.getElementById("setup-extension"),
    setupExtensionState: document.getElementById("setup-extension-state"),
    setupExtensionDesc: document.getElementById("setup-extension-desc"),
    setupBorderProtection: document.getElementById("setup-border-protection"),
    setupBorderProtectionState: document.getElementById("setup-border-protection-state"),
    setupBorderProtectionDesc: document.getElementById("setup-border-protection-desc"),
    setupRemoveHex: document.getElementById("setup-remove-hex"),
    setupRemoveHexState: document.getElementById("setup-remove-hex-state"),
    setupRemoveHexDesc: document.getElementById("setup-remove-hex-desc"),
    setupPlayerList: document.getElementById("setup-player-list"),
    addPlayerRow: document.getElementById("add-player-row"),
    newPlayerName: document.getElementById("new-player-name"),
    confirmAddPlayer: document.getElementById("confirm-add-player"),
    confirmNewGame: document.getElementById("confirm-new-game"),
    endgameModal: document.getElementById("endgame-modal"),
    endgameSummary: document.getElementById("endgame-summary"),
    toastRoot: document.getElementById("toast-root"),
    zoomLevel: document.getElementById("zoom-level"),
    zoomResetButton: document.getElementById("zoom-reset-button"),
    ruleSummary: document.getElementById("rule-summary"),
    ruleList: document.getElementById("rule-list"),
  };
}
