export function getDomRefs() {
  return {
    board: document.getElementById("board"),
    boardWrapper: document.querySelector(".board-wrapper"),
    boardContent: document.getElementById("board-content"),
    newGameButton: document.getElementById("new-game-button"),
    undoButton: document.getElementById("undo-button"),
    arenaTurnIndicator: document.getElementById("arena-turn-indicator"),
    turnPlayer: document.getElementById("turn-player"),
    statusMessage: document.getElementById("status-message"),
    scorePanel: document.getElementById("score-panel"),
    setupModal: document.getElementById("setup-modal"),
    setupGridSize: document.getElementById("setup-grid-size"),
    setupPlayerList: document.getElementById("setup-player-list"),
    addPlayerRow: document.getElementById("add-player-row"),
    newPlayerName: document.getElementById("new-player-name"),
    confirmAddPlayer: document.getElementById("confirm-add-player"),
    confirmNewGame: document.getElementById("confirm-new-game"),
    endgameModal: document.getElementById("endgame-modal"),
    endgameSummary: document.getElementById("endgame-summary"),
    toastRoot: document.getElementById("toast-root"),
    zoomLevel: document.getElementById("zoom-level"),
    zoomResetButton: document.getElementById("zoom-reset-button"),
  };
}
